site_name: VanBUG (Beta)
docs_dir: src
theme:
  name: material
  logo: images/logo.light.svg
  favicon: images/logo.svg
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
site_dir: dist
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.snippets:
      check_paths: True
      base_path: .
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
- styles/image-list.css
- styles/timeline.css
- styles/palette.css
plugins:
  - awesome-pages
  - search
  - include-markdown
nav:
  - Home: index.md
  - ...
